### PR TITLE
pthread-based locking for arc4random

### PR DESCRIPTION
**Pull request by neilcook**
For systems with no pthreads library (i.e. Windows), _ARC4_LOCK() and _ARC4_UNLOCK() are still stubs, which needs to be addressed by someone with Windows knowledge.

### CODE REVIEW

**Comment by neilcook** [comment]
I'm not sure why the transport test is failing - I don't see how it could be related to my change

**Comment by neilcook** [comment]
Fixed HAVE_PTHREADS define in configure.ac

**Comment by wtoorop** [comment]
Excellent.  Thanks!

**Comment by wtoorop** [comment]
Op 26-10-16 om 17:01 schreef Neil Cook:
> I'm not sure why the transport test is failing - I don't see how it
> could be related to my change

This might have been due to (connection tracking) issues on our side.
We have resolved this today.  I suspect the online unit tests will be
much more stable from now on.

**Pull request merged**
