### PR TITLE
Fixed eventloop

### PR DESCRIPTION
**Pull request by neilcook**
This seems to pass (except for one failure, which I notice also happens for the existing develop branch) the "normal" unit tests. However it seems to generate a ton of segfaults for the "stub only" unit tests, and I have no idea why, as that shouldn't make any difference.

### CODE REVIEW

**Comment by wtoorop** [comment]
Neil, thanks, I think I can explain why, but not today...
I will respond next Monday.

Op 15-12-16 om 16:10 schreef Neil Cook:

**Comment by neilcook** [comment]
Well I fixed the segfaults it would seem. I've found out you have to be quite careful in the event loop code when calling callbacks, because they can delete scheduled events - leading to free memory accesses, hence the segfaults. This wasn't a problem before, because the the data structure were static, but this causes problems with dynamic data structure. 

I cleaned this up to ensure that before calling _cb functions, I copy out the data needed, or create a temporary structure to hold the data.

Not sure if the remaining couple of errors have anything to do with my code - they seem to be infrastructure-related (travis issues?)

**Comment by wtoorop** [comment]
Happy New Year!

It is more than infrastructure...  I can reproduce.  I have to look into this.

 Ok with you if I take this to the 1.1.0 release?
I really have to do the 1.0.0 release with as little changes as possible (only bugfixes).

**Comment by neilcook** [comment]
I'm fine if you leave this until 1.1 - it would be good to have a release note stating the limitations in the meantime.

**Comment by neilcook** [comment]
Oh, and Happy New Year too!

**Comment by neilcook** [comment]
Yay, I finally figured out what the issue was. I got mostly there last year, but wasn't allocating new memory properly. Now I did it properly in the add/delete hash functions, and everything is looking good.

**Comment by wtoorop** [comment]
Thank you Neil!  Very happy with it.

I want to do a few changes myself before merging... provide it as another event loop extension, that will be the default when poll is available, but that will keep using select when it is not.  Once that is done, I'll merge.

After that I'll probably do some more modifications... I believe I could minimize the memory management (number of allocs and frees) a bit by putting more info in the getdns_eventloop_event (double linked list pointers?) and reusing the struct pollfd[] array, only reallocation when it needs to grow . Maybe the getdns_eventloop_event needs to become a little larger for that.  I'll have a look.
When memory allocations are needed, it would be nice if the event loop extension would use the custom memory functions.

**Comment by neilcook** [comment]
Hi, that all sounds good. I wonder which systems don't have poll() these days though!
Reusing memory would probably be a very good idea I agree, particularly the pollfd structure. Also, I didn't even realise there were custom memory functions, but now I know!

**Comment by neilcook** [comment]
I have one question on the changes you made - what is the purpose of timeout_id in _getdns_poll_eventloop? 

It's currently initialised to 0 and then never modified, and it is used in the following loop in poll_eventloop.c:

for (i = poll_loop->timeout_id + 1; i != poll_loop->timeout_id; i++) {
		if (find_event(&poll_loop->timeout_events, i) == NULL) {
			event->ev = add_event(mf, &poll_loop->timeout_events, i, event, get_now_plus(timeout));

			DEBUG_SCHED( "scheduled timeout at slot %d\n", (int)i);
			return GETDNS_RETURN_GOOD;
		}
	}

Was the idea to set it to "i" in the loop when an event is added, e.g.:

for (i = poll_loop->timeout_id + 1; i != poll_loop->timeout_id; i++) {
		if (find_event(&poll_loop->timeout_events, i) == NULL) {
			event->ev = add_event(mf, &poll_loop->timeout_events, i, event, get_now_plus(timeout));
                        timeout_id = i; /* ?? */
			DEBUG_SCHED( "scheduled timeout at slot %d\n", (int)i);
			return GETDNS_RETURN_GOOD;
		}
	}

**Comment by wtoorop** [comment]
That was the idea yes.. have (1) instead of (n) time for adding a timeout event.  However when working on the elimination on the  _getdns_eventloop_info malloc per schedule, I eventually had no need for an id (or fd which is in pollfd already) or the uthash any more, so this bug went away with that.

Another pull request with those updates is coming up soon...

**Pull request merged**
