### PR TITLE
call SSL_library_init() just once and lock with mutexes

### PR DESCRIPTION
**Pull request by neilcook**

### CODE REVIEW

**Comment by wtoorop** [comment]
I haven't forgotten about this...  It's just pending a opportunity for proper review

**Comment by neilcook** [comment]
No probs!

**Comment by neilcook** [comment]
It would be good if there was some movement on this. I notice huitema has added Windows locking for the arc4random functions, perhaps he could also do the same for these locks?

**Comment by wtoorop** [comment]
Absolutely!  I was only reluctant because of the introduction of stdbool.h.  I have experienced before that the size of a bool can vary at compile time.  This may be problematic when used in exposed structs.  The way you use it is safe though (because it is not exposed), but if more code will use it, it might eventually get exposed.

Why did you close the eventloop pull request?

**Comment by neilcook** [comment]
I'm just trying to fix the unit test issues before I reopen the event loop pull request - will hopefully do that today

**Pull request merged**
