### PR TITLE
Rename return_call_debugging to return_call_reporting. Update index.h…

### PR DESCRIPTION
**Pull request by saradickinson**
…tml with change of content.

### CODE REVIEW

**Comment by wtoorop** [comment]
OK, help me remind to do a spec update too though!

**Comment by saradickinson** [comment]
Yes - I was just writing you an email to ask if/how I could do it! Will make a note to remind you before the next release

**Comment by wtoorop** [comment]
Op 16-12-15 om 15:32 schreef saradickinson:
> Yes - I was just writing you an email to ask if/how I could do it! Will
> make a note to remind you before the next release

Well... you could try commit or make a pull request to
	https://github.com/getdnsapi/spec

But reminding me is fine too...
-- Willem

**Comment by saradickinson** [comment]
> On 16 Dec 2015, at 14:36, wtoorop <notifications@github.com> wrote:
> 
> Op 16-12-15 om 15:32 schreef saradickinson:
> > Yes - I was just writing you an email to ask if/how I could do it! Will
> > make a note to remind you before the next release
> 
> Well... you could try commit or make a pull request to
> https://github.com/getdnsapi/spec <https://github.com/getdnsapi/spec>

Yup, I’ll do that.

Sara.

**Pull request merged**
