### PR TITLE
Handle more harmless I/O error cases +

### PR DESCRIPTION
**Pull request by wtoorop**
- never exit on I/O errors
- never stop listening on I/O errors
- extended platfrom.[ch] with _getdns_strerror()

### CODE REVIEW

**Comment by banburybill** [comment]
This doesn't build on Windows. So far it fails in platform.c, with duplicate errno cases and an undeclared variable.

I've not finished looking. Other comments so far:

_getdns_socket_retry() sounds to me like it retries the operation, rather than checking the error code to see if it is one that should be retried. Perhaps rename to something like _getdns_errno_wants_retry()?

The Windows strerror() and perror() may produce different messages for the same error. I'd implemented perror() using strerror() and use a larger static buffer and FormatMessage() in strerror(). 

More soon...

**Comment by banburybill** [comment]
void _getdns_perror(const char *str)
{
        int errid = WSAGetLastError();
        if (str && *str != '\0')
                fprintf(stderr, "%s: ", str);
        fputs(_getdns_strerror(errid), stderr);
}

const char *_getdns_strerror(DWORD errnum)
{
        static char msg[256];

        *msg = '\0';
        FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM |
                          FORMAT_MESSAGE_IGNORE_INSERTS,
                      NULL,
                      errnum,
                      MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
                      msg,
                      sizeof(msg),
                      NULL);
        if (*msg == '\0')
                sprintf(msg, "Unknown error: %ld", errnum);
	return msg;
}

Compile still fails, now in platform.h from server.c. Looks like WSAENFILE does not exist.

**Comment by banburybill** [comment]
OK, so in platform.h. I now see _getdns_errno_retry() and _getdns_socket_retry(). Not a huge fan of macros here.

This patch gets things building for me. I think _getdns_resource_depletion() should check for a non-zero errno() to make sure it does the right thing if ENFILE or EMFILE aren't defined. Actually, while I think of it, I think _getdns_errno_retry() should also ensure that it doesn't accidentally match errno of 0 with an undefined error.

[builds.patch.gz](https://github.com/getdnsapi/getdns/files/1441491/builds.patch.gz)

**Comment by wtoorop** [comment]
Yes... I think testing for 0 is not necessary, because we only test errno after I/O failure.
Also, I read in the man page that errno is never zero:

       Valid error numbers are all nonzero; errno is never set to zero by any  sys‐
       tem call or library function.

However, it cannot harm either

**Comment by wtoorop** [comment]
I postpone your suggestion for _getdns_strerror() on windows, and do a thread safe version of thath (not returning a static buffer) after the release candidate.

**Comment by banburybill** [comment]
You are right that errno shouldn't be 0. In POSIX-land. The docs for WSAGetLastError() suggest that it can be reset to 0 by getsockopt() in Windows. I guess in an ideal world I'd call this a precondition and have an assert().

**Pull request merged**
